frontend:
  replicaCount: 1
  image:
    repository: onekeys/frontend
    tag: 38
    pullPolicy: IfNotPresent
  backendUrl: 10.101.127.42


postgres:
  replicaCount: 1
  image:
    repository: onekeys/postgres
    tag: 38
    pullPolicy: IfNotPresent
  database:
    name: perntodo
  storage:
    size: 3Gi

backend:
  replicaCount: 1
  image:
    repository: onekeys/backend
    tag: 38
    pullPolicy: IfNotPresent
  dbHost: 10.99.72.148
