frontend:
  replicaCount: 1
  image:
    repository: onekeys/frontend
    tag: 47
    pullPolicy: IfNotPresent
  backendUrl: 10.101.127.42


postgres:
  replicaCount: 1
  image:
    repository: onekeys/postgres
    tag: 47
    pullPolicy: IfNotPresent
  database:
    name: perntodo
  storage:
    size: 1Gi

backend:
  replicaCount: 1
  image:
    repository: onekeys/backend
    tag: 47
    pullPolicy: IfNotPresent
  dbHost: 10.97.126.119
