apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
